name: Build and Deploy Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Download custom icon
      run: |
        mkdir icons
        Invoke-WebRequest -Uri "https://github.com/chaos4455/py-crypt-messages/raw/main/icon.png" -OutFile "icons/icon.png"

    - name: Install PyInstaller and dependencies
      run: |
        python -m pip install pyinstaller Pillow cryptography

    - name: Install PyQt5 and dependencies
      run: |
        python -m pip install PyQt5 PyQt5-tools

    - name: Download Python script
      run: |
        Invoke-WebRequest -Uri "https://raw.githubusercontent.com/chaos4455/py-crypt-messages/main/encryptamensagens3.py" -OutFile "encryptamensagens3.py"

    - name: Build executable
      run: |
        pyinstaller --onefile --noconsole --icon=icons/icon.png encryptamensagens3.py

    - name: Check output
      run: |
        dir dist

    - name: Create versioned folder
      run: |
        if (Test-Path programa) {
          Write-Host "Directory 'programa' already exists."
        } else {
          New-Item -ItemType Directory -Path programa
        }
        $timestamp = Get-Date -Format "yyyyMMdd_HHmmss"
        Move-Item dist\encryptamensagens3.exe programa\app_v_${timestamp}.exe

    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Commit executable
      if: success()
      run: |
        git add programa\app_v_*.exe
        git commit -m "Add executable for version $timestamp"
        git push
