name: Build and Deploy Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check if pip is installed
      run: |
        python -m pip --version || (curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && python get-pip.py)
      continue-on-error: true

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        repository: chaos4455/py-crypt-messages
        ref: main

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pyqt5==5.15.4 pyqt5-tools==5.15.4 cryptography==35.0.0 pyinstaller

    - name: Build executable
      run: |
        pyinstaller --onefile --noconsole --icon=icon.ico encryptamensagens3.py
      env:
        ICON_PATH: ${{ github.workspace }}/icon.png

    - name: Check output directory
      run: |
        dir dist

    - name: Create versioned folder
      id: create_folder
      run: |
        if (!(Test-Path -Path programa)) {
          New-Item -ItemType Directory -Path programa
        }
        $timestamp = Get-Date -Format "yyyyMMdd_HHmmss"
        Move-Item dist\encryptamensagens3.exe programa\app_v_${timestamp}.exe

    - name: Commit executable
      if: success()
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add programa\app_v_*.exe
        git commit -m "Add executable for version $timestamp"
        git push
